name: Build
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint-check
