name: Build
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: "https://npm.pkg.github.com"
          scope: "@procesio"

      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PROCESIO_BOT_TOKEN }}

      - name: Build
        run: npm run build
